import {convert} from './engine.js';
// URL aplikasi web Apps Script (berakhir dengan /exec) — lihat apps-script/pwa-sync.gs. Kosong = tiada penyegerakan Sheet.
const SHEET_URL='https://script.google.com/macros/s/AKfycbwqfSO0zxUv9Dn1WNwg3gYMwtLR0eHcleLCjZ_00wr-7nZfHV4aan11wuMTNlavqkBEZw/exec';
const $=id=>document.getElementById(id);let dict=null,active=null,segments=[],kunci='',sheetVersi=null,syncState='',syncing=false,deferred=null,timer,size=32;
const STORE='jawi-pembetulan',OUTBOX='jawi-outbox',KUNCI='jawi-kunci',SHEET_CACHE='kamus-sheet',SHEET_KEY='./__kamus-sheet.json';
const readMap=key=>{const m=Object.create(null);try{for(const [k,v]of Object.entries(JSON.parse(localStorage.getItem(key)||'{}')))if(typeof v==='string'&&v.trim())m[k]=v;}catch{}return m;};
// corrections: pembetulan pada peranti (diutamakan). outbox: pembetulan yang belum sampai ke Sheet.
let corrections=readMap(STORE),outbox=readMap(OUTBOX);try{kunci=localStorage.getItem(KUNCI)||'';}catch{}
const canSync=()=>!!SHEET_URL&&!!kunci;
// Kamus aktif = kamus + pembetulan; dibina semula hanya apabila kamus/pembetulan berubah (indeks frasa enjin dicache ikut objek ini).
function persist(){if(dict)active=Object.assign(Object.create(null),dict,corrections);try{localStorage.setItem(STORE,JSON.stringify(corrections));localStorage.setItem(OUTBOX,JSON.stringify(outbox));}catch{toast('Pembetulan tidak dapat disimpan pada peranti ini.');}}
function remember(key,val){corrections[key]=val;if(canSync())outbox[key]=val;}
const toast=t=>{$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),3500);};
function syncText(){const saved=Object.keys(corrections).length,wait=Object.keys(outbox).length;
 if(!SHEET_URL)return saved?saved+' pembetulan disimpan pada peranti ini.':'Pembetulan akan disimpan pada peranti ini.';
 if(!kunci)return 'Disimpan pada peranti sahaja. Masukkan kunci guru untuk menyegerak ke Sheet.';
 if(wait)return wait+' pembetulan menunggu penyegerakan ke Sheet'+(syncState==='ralat'||!navigator.onLine?' (dicuba semula apabila dalam talian).':'…');
 return 'Pembetulan disimpan pada peranti dan disegerakkan dengan Sheet.';}
function showMeta(){const saved=Object.keys(corrections).length,wait=Object.keys(outbox).length;$('saved-count').textContent=syncText();$('export').disabled=saved===0;$('reset').disabled=saved===0&&wait===0;$('sync-key').hidden=!SHEET_URL;$('sync-key').textContent=kunci?'Kunci guru ✓':'Kunci guru';}
function counter(){const words=$('input').value.trim().match(/\S+/g);$('wordcount').textContent=(words?.length||0)+' perkataan';}
function invalidate(){segments=[];$('output').replaceChildren();const d=document.createElement('div');d.className='empty';const s=document.createElement('span');s.textContent='بسم الله';const p=document.createElement('p');p.textContent='Hasil Jawi akan muncul di sini.';d.append(s,p);$('output').append(d);$('copy').disabled=true;$('result-status').textContent='Sedia untuk penukaran';$('review').hidden=true;counter();}
function render(){const output=$('output');output.replaceChildren();const unknown=new Map();for(const s of segments){if(!s.p){output.append(document.createTextNode(s.j));continue;}unknown.set(s.r.toLowerCase(),s.j);const mark=document.createElement('mark');mark.textContent=s.j;mark.title='Semak: '+s.r;mark.tabIndex=0;mark.setAttribute('role','button');const focus=()=>{const row=[...$('review-list').children].find(x=>x.dataset.key===s.r.toLowerCase());row?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});row?.querySelector('input').focus({preventScroll:true});};mark.onclick=focus;mark.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focus();}};output.append(mark);}
 const saved=Object.keys(corrections).length;$('copy').disabled=!segments.length;$('result-status').textContent=unknown.size?unknown.size+' ejaan perlu semak':'Penukaran selesai';$('review').hidden=!segments.length||(unknown.size===0&&saved===0);$('review-title').textContent=unknown.size?unknown.size+' perkataan perlu semak':'Semakan selesai';showMeta();$('review-list').replaceChildren();for(const [key,val]of unknown){const row=document.createElement('div');row.className='review-row';row.dataset.key=key;const name=document.createElement('span');name.textContent=key;const input=document.createElement('input');input.value=val;input.lang='ms-Arab';input.setAttribute('aria-label','Ejaan Jawi bagi '+key);const b=document.createElement('button');b.textContent='Gunakan';const save=()=>{const v=input.value.trim();if(!v)return toast('Masukkan ejaan Jawi dahulu.');remember(key,v);persist();for(const s of segments)if(s.r?.toLowerCase()===key){s.j=v;s.p=false;}render();toast(canSync()?'Disimpan pada peranti. Menyegerak ke Sheet…':'Pembetulan disimpan pada peranti ini.');sync();};b.onclick=save;input.onkeydown=e=>{if(e.key==='Enter')save();};row.append(name,input,b);$('review-list').append(row);}}
async function run(text=$('input').value){if(!dict)throw new Error('Kamus belum tersedia.');if(typeof text!=='string'||!text.trim()){toast('Masukkan teks Rumi dahulu.');return null;}if(text.length>100000){toast('Had input ialah 100,000 aksara.');return null;}$('input').value=text;counter();segments=convert(text,active);render();return {jawi:segments.map(s=>s.j).join(''),perluSemak:[...new Set(segments.filter(s=>s.p).map(s=>s.r))]};}
$('input').oninput=invalidate;$('input').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run().catch(e=>toast(e.message));}};$('convert').onclick=()=>run().catch(e=>toast(e.message));$('clear').onclick=()=>{$('input').value='';invalidate();$('input').focus();};
$('copy').onclick=async()=>{const text=segments.map(s=>s.j).join('');try{await navigator.clipboard.writeText(text);toast('Hasil Jawi disalin.');}catch{const range=document.createRange();range.selectNodeContents($('output'));const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);toast('Pilih Salin pada peranti untuk menyalin teks terpilih.');}};
$('larger').onclick=()=>{size=Math.min(52,size+2);$('output').style.setProperty('--jawi-size',size+'px');};$('smaller').onclick=()=>{size=Math.max(22,size-2);$('output').style.setProperty('--jawi-size',size+'px');};
$('export').onclick=()=>{const lines=['Rumi\tJawi',...Object.entries(corrections).map(([k,v])=>k.replace(/[\t\r\n]/g,' ')+'\t'+v.replace(/[\t\r\n]/g,' '))];const url=URL.createObjectURL(new Blob(['﻿'+lines.join('\n')],{type:'text/tab-separated-values;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Pengecualian-Jawi.tsv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('import').onclick=()=>$('import-file').click();
$('import-file').onchange=async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;if(f.size>5e6)return toast('Fail terlalu besar (had 5 MB).');let n=0;for(const line of (await f.text()).replace(/^﻿/,'').split(/\r?\n/)){const [k,v]=line.split('\t');const key=k?.trim().normalize('NFC').toLowerCase(),val=v?.trim();if(!key||!val||(key==='rumi'&&val.toLowerCase()==='jawi'))continue;remember(key,val);n++;}if(!n)return toast('Tiada pasangan Rumi⇥Jawi ditemui. Gunakan fail TSV daripada Eksport.');persist();if(segments.length)await run();toast(n+' pembetulan diimport.');sync();};
$('reset').onclick=async()=>{const n=Object.keys(corrections).length;if(!confirm('Padam semua '+n+' pembetulan pada peranti ini?'+(SHEET_URL?' Entri yang sudah ada dalam Sheet tidak dipadam.':'')))return;corrections=Object.create(null);outbox=Object.create(null);persist();if(segments.length)await run();toast('Pembetulan dipadam.');};
// ---- Penyegerakan Sheet ----
async function api(query,body){const r=await fetch(SHEET_URL+query,body?{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(body)}:{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
async function flush(){for(const [rumi,jawi]of Object.entries(outbox)){const r=await api('',{action:'simpan',kunci,rumi,jawi});if(r.ok){if(outbox[rumi]===jawi)delete outbox[rumi];continue;}
 if(r.kunci===false){kunci='';try{localStorage.removeItem(KUNCI);}catch{}toast('Kunci guru tidak sah lagi. Masukkan kunci baharu untuk menyegerak.');return;}
 delete outbox[rumi];toast('Tidak dihantar ke Sheet: '+rumi+' — '+(r.ralat||'ralat'));}}
async function refresh(){const v=await api('?action=versi');if(!v.ok||v.versi===sheetVersi)return false;const r=await api('?action=kamus');
 // Lindungi daripada helaian yang terkosong secara tidak sengaja.
 if(!r.ok||!r.data||Object.keys(r.data).length<1000)return false;
 sheetVersi=r.versi;try{await (await caches.open(SHEET_CACHE)).put(SHEET_KEY,new Response(JSON.stringify({versi:r.versi,data:r.data}),{headers:{'Content-Type':'application/json'}}));}catch{}
 dict=Object.assign(Object.create(null),r.data);
 // Pembetulan yang kini sama dengan Sheet tidak perlu disimpan berasingan; suntingan guru di Sheet selepas ini akan diguna.
 for(const k of Object.keys(corrections))if(dict[k]===corrections[k]&&!(k in outbox))delete corrections[k];
 return true;}
// Jika dipanggil semasa penyegerakan sedang berjalan (cth. pembetulan baharu), ulang sekali lagi selepas selesai.
let syncAgain=false;
async function sync(){if(!SHEET_URL||!dict||!navigator.onLine)return;if(syncing){syncAgain=true;return;}syncing=true;let changed=false;try{if(kunci&&Object.keys(outbox).length){await flush();persist();showMeta();}changed=await refresh();syncState='ok';}catch{syncState='ralat';}finally{syncing=false;persist();}
 if(changed&&segments.length)await run().catch(()=>{});else showMeta();
 if(syncAgain){syncAgain=false;sync();}}
$('sync-key').onclick=()=>{$('key-input').value=kunci;$('key-remove').hidden=!kunci;$('key-dialog').showModal();$('key-input').focus();};
$('key-cancel').onclick=()=>$('key-dialog').close();
$('key-remove').onclick=()=>{kunci='';try{localStorage.removeItem(KUNCI);}catch{}outbox=Object.create(null);persist();showMeta();$('key-dialog').close();toast('Kunci dibuang. Pembetulan disimpan pada peranti sahaja.');};
$('key-form').onsubmit=async e=>{e.preventDefault();const k=$('key-input').value.trim();if(!k)return toast('Masukkan kunci guru.');if(!navigator.onLine)return toast('Perlu dalam talian untuk mengesahkan kunci.');$('key-save').disabled=true;
 try{const r=await api('',{action:'semak',kunci:k});if(!r.ok)throw Error(r.ralat||'Kunci guru tidak sah.');kunci=k;try{localStorage.setItem(KUNCI,k);}catch{}
  // Pembetulan sedia ada pada peranti turut dihantar ke Sheet.
  for(const [a,b]of Object.entries(corrections))outbox[a]=b;persist();$('key-dialog').close();toast('Kunci disahkan. Menyegerak ke Sheet…');sync();}
 catch(err){toast(err.message==='Failed to fetch'?'Tidak dapat menghubungi Sheet.':err.message);}finally{$('key-save').disabled=false;}};
function online(){$('connection').textContent=navigator.onLine?'Dalam talian':'Luar talian';}window.addEventListener('online',()=>{online();sync();});window.addEventListener('offline',()=>{online();showMeta();});online();
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')sync();});setInterval(()=>{if(document.visibilityState==='visible')sync();},5*60*1000);
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;});window.addEventListener('appinstalled',()=>{$('install').hidden=true;toast('Aplikasi Jawi dipasang.');});if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('install').hidden=true;
$('install').onclick=async()=>{if(deferred){await deferred.prompt();const choice=await deferred.userChoice;deferred=null;if(choice.outcome==='accepted')$('install').hidden=true;return;}$('install-message').textContent=/iPhone|iPad|iPod/.test(navigator.userAgent)?'Buka pautan ini dalam Safari. Tekan Kongsi, kemudian pilih Add to Home Screen / Tambah ke Skrin Utama.':'Buka menu pelayar dan pilih Pasang aplikasi atau Add to Home screen. Jika pilihan belum muncul, tunggu muatan selesai dan buka semula halaman.';$('install-help').showModal();};$('close-help').onclick=()=>$('install-help').close();
// Semak versi baharu setiap kali aplikasi dibuka semula; service worker baharu mengambil alih secara senyap (skipWaiting + clients.claim).
function watchUpdates(){navigator.serviceWorker.register('./sw.js').then(reg=>document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')reg.update().catch(()=>{});})).catch(()=>toast('Muatan luar talian belum tersedia.'));}
// Salinan Sheet terakhir pada peranti (jika ada) diguna dahulu; kamus.json hanya untuk lawatan pertama / tanpa Sheet.
async function cachedSheet(){if(!SHEET_URL)return null;try{const r=await (await caches.open(SHEET_CACHE)).match(SHEET_KEY);if(r){const j=await r.json();if(j?.data){sheetVersi=j.versi;return j.data;}}}catch{}return null;}
async function load(){try{let data=await cachedSheet();if(!data){const r=await fetch('./kamus.json');if(!r.ok)throw Error();data=await r.json();}dict=Object.assign(Object.create(null),data);active=Object.assign(Object.create(null),dict,corrections);$('convert').disabled=false;$('convert').textContent='Tukar ke Jawi';if('serviceWorker'in navigator)watchUpdates();sync();}catch{toast('Kamus gagal dimuatkan. Semak sambungan.');$('convert').disabled=false;$('convert').textContent='Cuba muat semula';$('convert').onclick=()=>location.reload();}}
load();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'convert_rumi_to_jawi',title:'Tukar Rumi kepada Jawi',description:'Tukar teks Rumi dan paparkan hasil Jawi serta perkataan yang perlu disemak.',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.text!=='string'||!input.text.trim()||input.text.length>100000)throw Error('Masukkan teks antara 1 hingga 100,000 aksara.');return await run(input.text);}})).catch(()=>{});}catch{}}
