import {convert} from './engine.js';
const $=id=>document.getElementById(id);let dict=null,segments=[],corrections=Object.create(null),deferred=null,timer,size=32;
const toast=t=>{$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(timer);timer=setTimeout(()=>$('toast').classList.remove('show'),3500);};
function counter(){const words=$('input').value.trim().match(/\S+/g);$('wordcount').textContent=(words?.length||0)+' perkataan';}
function invalidate(){segments=[];$('output').replaceChildren();const d=document.createElement('div');d.className='empty';const s=document.createElement('span');s.textContent='بسم الله';const p=document.createElement('p');p.textContent='Hasil Jawi akan muncul di sini.';d.append(s,p);$('output').append(d);$('copy').disabled=true;$('result-status').textContent='Sedia untuk penukaran';$('review').hidden=true;counter();}
function render(){const output=$('output');output.replaceChildren();const unknown=new Map();for(const s of segments){if(!s.p){output.append(document.createTextNode(s.j));continue;}unknown.set(s.r.toLowerCase(),s.j);const mark=document.createElement('mark');mark.textContent=s.j;mark.title='Semak: '+s.r;mark.tabIndex=0;mark.setAttribute('role','button');const focus=()=>{const row=[...$('review-list').children].find(x=>x.dataset.key===s.r.toLowerCase());row?.scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});row?.querySelector('input').focus({preventScroll:true});};mark.onclick=focus;mark.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();focus();}};output.append(mark);}
 $('copy').disabled=!segments.length;$('result-status').textContent=unknown.size?unknown.size+' ejaan perlu semak':'Penukaran selesai';$('review').hidden=unknown.size===0&&Object.keys(corrections).length===0;$('review-title').textContent=unknown.size?unknown.size+' perkataan perlu semak':'Semakan selesai';$('export').disabled=Object.keys(corrections).length===0;$('review-list').replaceChildren();for(const [key,val]of unknown){const row=document.createElement('div');row.className='review-row';row.dataset.key=key;const name=document.createElement('span');name.textContent=key;const input=document.createElement('input');input.value=val;input.setAttribute('aria-label','Ejaan Jawi bagi '+key);const b=document.createElement('button');b.textContent='Gunakan';const save=()=>{const v=input.value.trim();if(!v)return toast('Masukkan ejaan Jawi dahulu.');corrections[key]=v;for(const s of segments)if(s.r?.toLowerCase()===key){s.j=v;s.p=false;}render();toast('Pembetulan digunakan untuk sesi ini.');};b.onclick=save;input.onkeydown=e=>{if(e.key==='Enter')save();};row.append(name,input,b);$('review-list').append(row);}}
async function run(text=$('input').value){if(!dict)throw new Error('Kamus belum tersedia.');if(typeof text!=='string'||!text.trim()){toast('Masukkan teks Rumi dahulu.');return null;}if(text.length>100000){toast('Had input ialah 100,000 aksara.');return null;}$('input').value=text;counter();segments=convert(text,Object.assign(Object.create(null),dict,corrections));render();return {jawi:segments.map(s=>s.j).join(''),perluSemak:[...new Set(segments.filter(s=>s.p).map(s=>s.r))]};}
$('input').oninput=invalidate;$('input').onkeydown=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();run().catch(e=>toast(e.message));}};$('convert').onclick=()=>run().catch(e=>toast(e.message));$('clear').onclick=()=>{$('input').value='';invalidate();$('input').focus();};
$('copy').onclick=async()=>{const text=segments.map(s=>s.j).join('');try{await navigator.clipboard.writeText(text);toast('Hasil Jawi disalin.');}catch{const range=document.createRange();range.selectNodeContents($('output'));const sel=window.getSelection();sel.removeAllRanges();sel.addRange(range);toast('Pilih Salin pada peranti untuk menyalin teks terpilih.');}};
$('larger').onclick=()=>{size=Math.min(52,size+2);$('output').style.setProperty('--jawi-size',size+'px');};$('smaller').onclick=()=>{size=Math.max(22,size-2);$('output').style.setProperty('--jawi-size',size+'px');};
$('export').onclick=()=>{const lines=['Rumi\tJawi',...Object.entries(corrections).map(([k,v])=>k.replace(/[\t\r\n]/g,' ')+'\t'+v.replace(/[\t\r\n]/g,' '))];const url=URL.createObjectURL(new Blob(['\ufeff'+lines.join('\n')],{type:'text/tab-separated-values;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='Pengecualian-Jawi.tsv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
function online(){$('connection').textContent=navigator.onLine?'Dalam talian':'Luar talian';}window.addEventListener('online',online);window.addEventListener('offline',online);online();
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;});window.addEventListener('appinstalled',()=>{$('install').hidden=true;toast('Aplikasi Jawi dipasang.');});if(matchMedia('(display-mode: standalone)').matches||navigator.standalone)$('install').hidden=true;
$('install').onclick=async()=>{if(deferred){await deferred.prompt();const choice=await deferred.userChoice;deferred=null;if(choice.outcome==='accepted')$('install').hidden=true;return;}$('install-message').textContent=/iPhone|iPad|iPod/.test(navigator.userAgent)?'Buka pautan ini dalam Safari. Tekan Kongsi, kemudian pilih Add to Home Screen / Tambah ke Skrin Utama.':'Buka menu pelayar dan pilih Pasang aplikasi atau Add to Home screen. Jika pilihan belum muncul, tunggu muatan selesai dan buka semula halaman.';$('install-help').showModal();};$('close-help').onclick=()=>$('install-help').close();
async function load(){try{const r=await fetch('./kamus.json');if(!r.ok)throw Error();dict=Object.assign(Object.create(null),await r.json());$('convert').disabled=false;$('convert').textContent='Tukar ke Jawi';$('dictionary-status').textContent=Object.keys(dict).length.toLocaleString('en-US')+' entri kamus & pengecualian';if('serviceWorker'in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>toast('Muatan luar talian belum tersedia.'));}}catch{$('dictionary-status').textContent='Kamus gagal dimuatkan. Semak sambungan.';$('convert').disabled=false;$('convert').textContent='Cuba muat semula';$('convert').onclick=()=>location.reload();}}
load();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'convert_rumi_to_jawi',title:'Tukar Rumi kepada Jawi',description:'Tukar teks Rumi dan paparkan hasil Jawi serta perkataan yang perlu disemak.',inputSchema:{type:'object',properties:{text:{type:'string'}},required:['text'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:true},execute:async input=>{if(!input||typeof input.text!=='string'||!input.text.trim()||input.text.length>100000)throw Error('Masukkan teks antara 1 hingga 100,000 aksara.');return await run(input.text);}})).catch(()=>{});}catch{}}
